### Hu Moments ( or rather Hu moment invariants ) are a set of 7 numbers calculated using central moments that are invariant to image transformations. The first 6 moments have been proved to be invariant to translation, scale, and rotation, and reflection. While the 7th moment’s sign changes for image reflection.


#### here we divide images into syllables:

In [63]:
#import cv2
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pylab as pl
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import accuracy_score, classification_report
from sklearn.cluster import MiniBatchKMeans
from preprocess import *
from collections import Counter
import cv2
import math
from skimage.transform import pyramid_reduce
from sklearn.metrics import accuracy_score
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [64]:
A = load_Dataset("../fonts-dataset/Scheherazade New/*.jpeg")
B= load_Dataset("../fonts-dataset/Lemonada/*.jpeg")
C= load_Dataset("../fonts-dataset/Marhey/*.jpeg")
D= load_Dataset("../fonts-dataset/IBM Plex Sans Arabic/*.jpeg")

400
400
400
400


In [65]:
A, A_TEST = train_test_split(A, test_size=0.2)
B, B_TEST = train_test_split(B, test_size=0.2)
C, C_TEST = train_test_split(C, test_size=0.2)
D, D_TEST = train_test_split(D, test_size=0.2)

In [66]:
A_PROCESSED = []
for img in A:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    A_PROCESSED.extend(img)
B_PROCESSED = []
for img in B:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    B_PROCESSED.extend(img)
C_PROCESSED = []
for img in C:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    C_PROCESSED.extend(img)
D_PROCESSED = []
for img in D:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    D_PROCESSED.extend(img)

In [67]:
A_moms=[]
for im in A_PROCESSED:
    moments = cv2.moments(im) 
    huMoments = cv2.HuMoments(moments)
    huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
    A_moms.append(huMoments.flatten())
B_moms=[]
for im in B_PROCESSED:
    moments = cv2.moments(im) 
    huMoments = cv2.HuMoments(moments)
    huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
    B_moms.append(huMoments.flatten())
C_moms=[]
for im in C_PROCESSED:
    moments = cv2.moments(im) 
    huMoments = cv2.HuMoments(moments)
    huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
    C_moms.append(huMoments.flatten())
D_moms=[]
for im in D_PROCESSED:
    moments = cv2.moments(im) 
    huMoments = cv2.HuMoments(moments)
    huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
    D_moms.append(huMoments.flatten())

In [68]:
train_labels=np.concatenate((np.zeros(len(A_moms)),np.ones(len(B_moms)),np.full(len(C_moms),2),np.full(len(D_moms),3)))

In [69]:
combined_list=A_moms+B_moms+C_moms+D_moms

In [70]:
def train_knn_classifier(k, train_features, train_labels):
    # Create KNN classifier object
    knn_classifier = KNeighborsClassifier(n_neighbors=k,n_jobs=-1,weights='distance',metric='euclidean',algorithm='auto')
    
    # Train the classifier
    knn_classifier.fit(train_features, train_labels)
    
    return knn_classifier

In [71]:
knn_classifier = train_knn_classifier(5,combined_list,train_labels)

In [72]:
A_TPROCESSED = []
for img in A_TEST:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    A_TPROCESSED.append(img)
B_TPROCESSED = []
for img in B_TEST:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    B_TPROCESSED.append(img)
C_TPROCESSED = []
for img in C_TEST:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    C_TPROCESSED.append(img)
D_TPROCESSED = []
for img in D_TEST:
    img = threshold_image(img)
    img= assure_white_bg(img)
    img=get_words(img)
    D_TPROCESSED.append(img)

In [73]:
print(knn_classifier.predict(D_moms))

[3. 3. 3. ... 3. 3. 3.]


In [74]:
A_Tmoms=[]
for im in A_TPROCESSED:
    x=[]
    for i in im:
        moments = cv2.moments(i) 
        huMoments = cv2.HuMoments(moments)
        huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
        x.append(huMoments.flatten())
    A_Tmoms.append(x)
B_Tmoms=[]
for im in B_TPROCESSED:
    x=[]
    for i in im:
        moments = cv2.moments(i) 
        huMoments = cv2.HuMoments(moments)
        huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
        x.append(huMoments.flatten())
    B_Tmoms.append(x)
C_Tmoms=[]
for im in C_TPROCESSED:
    x=[]
    for i in im:
        moments = cv2.moments(i) 
        huMoments = cv2.HuMoments(moments)
        huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
        x.append(huMoments.flatten())
    C_Tmoms.append(x)
D_Tmoms=[]
for im in D_TPROCESSED:
    x=[]
    for i in im:
        moments = cv2.moments(i) 
        huMoments = cv2.HuMoments(moments)
        huMoments = -np.sign(huMoments) * np.log10(np.abs(huMoments+0.001))
        x.append(huMoments.flatten())
    D_Tmoms.append(x)

In [75]:
counts = 0 
for words in A_Tmoms:
    words=np.array(words)
    words=words.reshape(-1,7)
    preds=knn_classifier.predict(words)
    preds_count= Counter(preds)
    most_common_label = preds_count.most_common(1)[0][0]
    if most_common_label == 0:
        counts+=1
    print(preds)
    print(counts)
print("A: ", counts*100/len(A_TPROCESSED))

[0. 2. 0. 3. 2. 0. 3. 2.]
1
[0. 2. 1. 0. 1. 0. 1. 0. 0. 0. 3. 2. 3. 2. 2. 0. 0. 1. 2. 0. 2. 1. 0. 0.
 0. 1. 2. 0. 0. 0. 0. 0. 0. 2. 2. 2. 0. 2. 1. 3. 0. 3. 1. 1. 0. 2. 0. 2.
 0. 3. 0. 0. 2. 3. 0. 1. 0. 2. 1. 1. 0. 0. 0. 0. 2. 1. 2. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 2. 0. 0. 1. 0. 1. 2. 3. 0. 0. 3. 0. 0. 0. 2. 3. 2. 0. 0.
 0. 2. 1. 0. 2. 3. 1. 0. 1. 1. 0. 0. 1. 3. 1. 2. 3. 2. 0. 2.]
2
[0. 3. 3. 0. 2. 0. 2. 0. 1. 2. 3. 3. 2. 2. 0. 1. 2. 2. 0. 0. 2. 3. 3. 0.
 0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 1. 0. 0. 1. 0. 0. 0. 0. 2.
 0. 1. 0. 0. 0. 0.]
3
[2. 0. 0. 3. 2. 0. 2. 0. 2. 1. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 3. 3. 0. 0. 0. 0. 2. 1. 2. 0. 3. 0. 3. 2. 1. 0. 0. 0. 1. 0. 2. 1. 1.
 0. 3. 2. 1. 0. 3. 1. 3. 0. 1. 1. 1. 0. 1.]
4
[0. 3. 0. 0. 3. 3. 0. 0. 0. 0. 3. 2. 2. 1. 0. 0. 3. 3. 0. 2. 2. 2. 0. 1.
 1. 3. 0. 2. 0. 0. 1. 1. 2. 3. 0. 0. 0. 1. 3. 0. 0. 1. 1. 3. 0. 0. 1. 1.
 0. 0. 0. 2. 0. 2. 2. 0. 0. 2. 3. 2. 0. 0. 3. 0. 1. 3. 0. 1. 0. 0. 0. 0.
 0. 0. 2. 2. 3. 3. 3. 0. 0. 0. 0. 0. 

In [76]:
for words in B_Tmoms:
    words=np.array(words)
    words=words.reshape(-1,7)
    preds=knn_classifier.predict(words)
    preds_count= Counter(preds)
    most_common_label = preds_count.most_common(1)[0][0]
    if most_common_label == 1:
        counts+=1
    print(preds)
    print(counts)
print("B: ", counts*100/(len(A_TPROCESSED)*2))

[1. 3. 1. 1. 0. 2. 0. 3. 3. 1. 3. 0. 2. 0. 1. 1. 1. 0. 3. 2. 3. 3. 1. 0.
 2. 1. 1. 1. 1. 1. 1. 2. 3. 3. 1. 2. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 3.
 0. 3. 1. 3. 0. 1. 3. 1. 1. 0. 3. 1. 1. 3. 1. 2. 1. 0. 1. 1.]
67
[1. 1. 3. 0. 1. 1. 1. 1. 1. 2. 2. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 2. 1.
 1. 0. 3. 2. 3. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 0. 1. 1. 1. 1. 1. 3.
 1. 3. 2. 1. 1. 1. 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 3. 1. 1. 1. 2. 2. 1. 1.
 1. 2. 1. 2. 2. 1. 1. 3. 1. 1.]
68
[1. 1. 1. 1. 2. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 3. 1.
 1. 2. 1. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
69
[1. 2. 2. 1. 1. 3. 3. 2. 3. 1. 1. 1. 2. 3. 1. 2. 3. 3. 3. 0. 1. 3. 1. 3.
 1. 3. 1. 1. 1. 3. 1. 1. 1. 3. 1. 1. 2. 1. 2. 3. 3. 3. 2. 3. 2. 2. 1. 1.
 1. 2. 2. 3. 2. 2. 2. 2. 2. 3. 1. 1. 1. 3. 2. 2. 3. 2. 3. 3. 3. 3. 3. 3.
 1. 3. 1. 3. 1. 1. 3. 3. 0.]
69
[2. 0. 2. 2. 2. 2. 2. 0. 1. 3. 0. 2. 1. 3. 2. 2. 0. 2. 2. 1. 1. 1. 1. 1.
 2. 1. 0. 1. 3. 1. 0. 1. 1. 3. 1. 3. 3. 1. 1. 2. 3.]
70
[1. 1. 1. 1. 3. 2. 1. 1. 1. 1

In [77]:
for words in C_Tmoms:
    words=np.array(words)
    words=words.reshape(-1,7)
    preds_count= Counter(preds)
    most_common_label = preds_count.most_common(1)[0][0]
    if most_common_label == 2:
        counts+=1
    print(preds)
    print(counts)
print("C: ", counts*100/(len(A_TPROCESSED)*3))

[1. 0. 2. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 0. 0. 3. 3.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 0. 1. 2. 1. 1. 1. 1. 0.
 2. 2. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
136
[1. 0. 2. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 0. 0. 3. 3.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 0. 1. 2. 1. 1. 1. 1. 0.
 2. 2. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
136
[1. 0. 2. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 0. 0. 3. 3.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 0. 1. 2. 1. 1. 1. 1. 0.
 2. 2. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
136
[1. 0. 2. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 0. 0. 3. 3.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 0. 1. 2. 1. 1. 1. 1. 0.
 2. 2. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
136
[1. 0. 2. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 0. 0. 3. 3.
 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 3. 0. 1. 2. 1. 1. 1. 1. 0.
 2. 2. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
136
[1. 0. 2. 1. 2. 3. 2. 1. 1. 1. 1. 1. 2. 3. 1. 1. 1. 1. 1. 2. 0. 0. 3. 3.
 1

In [78]:
for words in D_Tmoms:
    words=np.array(words)
    words=words.reshape(-1,7)
    preds=knn_classifier.predict(words)
    preds_count= Counter(preds)
    most_common_label = preds_count.most_common(1)[0][0]
    if most_common_label == 3:
        counts+=1
    print(preds)
    print(counts)
print("D: ", counts*100/(len(A_TPROCESSED)*4))

[3. 3. 1. 3. 3. 3. 0. 3. 3. 3. 0. 0. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 0. 1.
 3. 1. 1. 3. 3. 3. 0. 1. 1. 1. 3. 3. 3. 3. 0. 1. 3. 1. 3. 3. 3. 3. 3. 0.
 3. 1. 1. 3. 3. 3. 3. 3. 1. 1. 3. 3. 0. 0. 3. 0. 3. 3. 3. 3. 3. 1. 3. 3.
 3. 3. 3. 2. 3. 3. 1. 3. 3. 1. 0. 2. 1. 3. 3. 1. 3. 3.]
137
[3. 0. 2. 1. 3. 2. 0. 1. 3. 3. 3. 2. 1. 2. 3. 1. 2. 3. 1. 2. 2. 3. 0. 3.
 2. 1. 1. 3. 3. 3. 0. 1. 0. 1. 2. 0. 2. 0. 2. 1. 3. 0. 3. 3. 1. 0. 3. 3.
 3. 3. 2. 0. 0. 2. 3. 1. 3. 0. 2. 0. 2. 1. 2. 2. 1. 2. 0. 3. 3. 1. 3. 2.
 3. 3. 1. 2. 0. 3. 1. 0. 2. 0. 3. 3. 0. 2. 2. 3. 3. 3. 0. 0. 3. 0.]
138
[2. 1. 3. 3. 3. 1. 0. 0. 1. 0. 3. 3. 1. 0. 2. 1. 3. 3. 3. 0. 2. 1. 0.]
139
[0. 0. 3. 3. 1. 0. 3. 0. 3. 3. 3. 1. 3. 2. 0. 3. 2. 0. 0. 0. 0. 3. 3. 2.
 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 1. 3. 0. 3. 0. 3. 3. 3. 3. 3. 3. 3. 3. 1.
 3. 3. 2. 0. 0. 2. 3. 0. 2. 1. 3. 3. 1. 1. 3. 2. 2. 3. 3. 1. 2. 3. 0. 2.
 1. 3. 3. 0. 1. 3. 1. 3. 3. 1. 0. 3. 2. 3. 3. 0. 3. 3. 2. 3. 3. 1. 3. 1.
 1. 0. 3. 3. 1. 3. 0. 0. 1. 0. 3. 3. 2. 3. 3. 3. 2. 3.]
140
[3.